### ISSUE TITLE
Calculate the original price of a product

### ISSUE THREAD

**Issue by missKatiaPunter** [EDGENortheastern/pull-request-pair-practice#1]
# Task 1 ticket

You need to write a function to calculate **the original price of a product.**

## Acceptance criteria:

- [x] function is called `original_price`
- [x] it takes two parameters `discounted_price` and `sale_percentage` - both decimals
- [x] it returns a decimal rounded to two decimal places
- [x] passes tests in test_task_1.py

## Example:

An item costs £75 after a 25% discount.
The function should return 100.00
