### ISSUE TITLE
Find the middle element

### ISSUE THREAD

**Issue by missKatiaPunter** [EDGENortheastern/pull-request-pair-practice#2]
# Task 2 ticket

You need to write a function to return **the index of the numerical middle element**

## Acceptance criteria:

- [x] function is called `return_middle`
- [x] it takes one parameter, `triplet` - a list of integers
- [x] it returns the index of the numerical element that lies between the other two elements
- [x] passes tests in test_task_2.py

## Example:

- A function is called with [2, 3, 1]
- The function should return 0

**Comment by Muhammedsinanck** [comment]
Hi i am interested in this issue , can you assign this to me.
