### ISSUE TITLE
# Task 5 ticket  ✏️

### ISSUE THREAD

**Issue by missKatiaPunter** [EDGENortheastern/pull-request-pair-practice#8]
# Task 5 ticket 

You need to write a **Class Item**.

## Acceptance criteria:

- [ ] the class takes no parameters
- [ ] the class should have three attributes: **_type_**, **_name_** and _**age**_
- [ ] each class attribute should have a setter function
- [ ] setters should be named: set_type etc
- [ ] passes tests in test_task_4.py

## Example:

```
    grasshopper_lala = Insect()
    grasshopper_lala.set_type('grasshopper')
    grasshopper_lala.set_name('Lala')
    grasshopper_lala.set_age(4)
```

should set type to 'grasshopper' etc.
